services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway-container
    restart: on-failure
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - SERVICE_SEARCH_PORT=${SERVICE_SEARCH_PORT}
    env_file:
      - ./.env
    networks:
      - docker-network
    depends_on:
      - service-search

  service-search:
    build:
      context: .
      dockerfile: service-search/Dockerfile
    container_name: service-search-container
    restart: on-failure
    ports:
      - "${SERVICE_SEARCH_PORT}:${SERVICE_SEARCH_PORT}"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVICE_SEARCH_PORT=${SERVICE_SEARCH_PORT}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=${SPRING_REDIS_PORT}
      - SPRING_DATA_REDIS_TIMEOUT=${SPRING_REDIS_TIMEOUT}
    env_file:
      - ./.env
    networks:
      - docker-network
    depends_on:
      - redis

  redis:
    image: redis:7.4-alpine
    container_name: redis-container
    restart: always
    ports:
      - "${REDIS_HOST_PORT:-6379}:6379"
    networks:
      - docker-network
    volumes:
      - redis-data:/data

networks:
  docker-network:
    driver: bridge

volumes:
  redis-data:
    driver: local