server:
  port: ${SERVER_PORT_API_GATEWAY}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME_API_GATEWAY}
  config:
    import: optional:file:../../.env
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${CORS_ALLOWED_ORIGINS}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Session-Id
              - Content-Type
              - Authorization
            allowCredentials: true
      routes:
        - id: service-search-api
          uri: http://localhost:${SERVER_PORT_SERVICE_SEARCH}
          predicates:
            - Path=/api/v1/search/**

        - id: service-search-openapi
          uri: http://localhost:${SERVER_PORT_SERVICE_SEARCH}
          predicates:
            - Path=/v3/api-docs/service-search
          filters:
            - RewritePath=/v3/api-docs/service-search, /v3/api-docs

        - id: service-users-api
          uri: http://localhost:${SERVER_PORT_SERVICE_USERS}
          predicates:
              - Path=/api/v1/users/**

        - id: service-users-avatars
          uri: http://localhost:${SERVER_PORT_SERVICE_USERS}
          predicates:
            - Path=/avatars/**

        - id: service-users-openapi
          uri: http://localhost:${SERVER_PORT_SERVICE_USERS}
          predicates:
            - Path=/v3/api-docs/service-users
          filters:
            - RewritePath=/v3/api-docs/service-users, /v3/api-docs

        - id: service-monitoring-openapi
          uri: http://localhost:${SERVER_PORT_SERVICE_MONITORING}
          predicates:
            - Path=/v3/api-docs/service-monitoring
          filters:
            - RewritePath=/v3/api-docs/service-monitoring, /v3/api-docs

        - id: service-monitoring-test-price-alert
          uri: http://localhost:${SERVER_PORT_SERVICE_MONITORING}
          predicates:
            - Path=/api/v1/send-test-alert

        - id: service-notifications-openapi
          uri: http://localhost:${SERVER_PORT_SERVICE_NOTIFICATIONS}
          predicates:
            - Path=/v3/api-docs/service-notifications
          filters:
            - RewritePath=/v3/api-docs/service-notifications, /v3/api-docs

springdoc:
  swagger-ui:
    path: /api-docs
    urls:
      - name: service-search
        url: /v3/api-docs/service-search
      - name: service-users
        url: /v3/api-docs/service-users
      - name: service-monitoring
        url: /v3/api-docs/service-monitoring
      - name: service-notifications
        url: /v3/api-docs/service-notifications
  api-docs:
    groups:
      enabled: true