server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:file:../../.env
  cloud:
    gateway:
      routes:
        - id: service-search-api
          uri: http://localhost:${SERVICE_SEARCH_PORT:8082}
          predicates:
            - Path=/api/v1/**

        - id: service-search-openapi
          uri: http://localhost:${SERVICE_SEARCH_PORT:8082}
          predicates:
            - Path=/v3/api-docs/service-search
          filters:
            - RewritePath=/v3/api-docs/service-search, /v3/api-docs

#        - id: service-users-api
#          uri: http://localhost:${SERVICE_USERS_PORT:8083}
#          predicates:
#              - Path=/api/v1/**

springdoc:
  swagger-ui:
    path: /api-docs
    urls:
      - name: service-search
        url: /v3/api-docs/service-search
#      - name: service-users
#        url: /v3/api-docs/service-users
  api-docs:
    groups:
      enabled: true