#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE "$SERVICE_USERS_DB_NAME";
    CREATE DATABASE "$SERVICE_MONITORING_DB_NAME";
    CREATE DATABASE "$SERVICE_NOTIFICATIONS_DB_NAME";
EOSQL
